name: epoint_deal_plugin
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.10.1 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  auto_size_text: ^3.0.0
  http: ^0.13.5
  url_launcher: ^6.1.5
  intl: ^0.17.0
  image_picker: ^0.8.5+3
  draggable_expandable_fab: ^1.0.0
  shimmer: ^2.0.0
  cached_network_image: ^3.2.1
  webview_flutter_plus: ^0.3.0+2
  keyboard_actions: ^4.0.1
  image: ^3.0.0
  dotted_border: ^2.0.0+2
  auto_size_text_field: ^2.1.0
  rxdart: ^0.27.4
  file_picker: ^5.2.4
  smooth_star_rating: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  plugin:
    platforms:
      android:
        package: com.example.epoint_deal_plugin
        pluginClass: EpointDealPlugin
      ios:
        pluginClass: EpointDealPlugin
      web:
        pluginClass: EpointDealPluginWeb
        fileName: epoint_deal_plugin_web.dart

  # To add assets to your plugin package, add an assets section, like this:
  assets:
    - assets/languages/
    - assets/icons/
    - assets/images/

