name: epoint_deal_plugin
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.1.4
  auto_size_text: ^3.0.0
  http: ^0.13.6
  url_launcher: ^6.1.11
  intl: ^0.18.1
  image_picker: ^0.8.8
  draggable_expandable_fab: ^1.0.0
  shimmer: ^3.0.0
  cached_network_image: ^3.2.3
  keyboard_actions: ^4.2.0
  image: ^4.0.17
  dotted_border: ^2.0.0+3
  auto_size_text_field: ^2.2.1
  rxdart: ^0.27.7
  file_picker: ^5.2.10
  smooth_star_rating_null_safety: ^1.0.4+2
  webview_flutter: ^4.2.2
  flutter_widget_from_html: ^0.10.1
  mime: ^1.0.4
  aws_s3_upload: ^1.5.0
  connectivity_plus: ^4.0.1
  collection: ^1.15.0-nullsafety.4

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  plugin:
    platforms:
      android:
        package: com.example.epoint_deal_plugin
        pluginClass: EpointDealPlugin
      ios:
        pluginClass: EpointDealPlugin
      web:
        pluginClass: EpointDealPluginWeb
        fileName: epoint_deal_plugin_web.dart

  # To add assets to your plugin package, add an assets section, like this:
  assets:
    - assets/languages/
    - assets/icons/
    - assets/images/

